apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: guestbook-app-image
  namespace: "ci" # {"type":"string","x-kustomize":{"setter":{"name":"namespace","value":"ci"}}}
spec:
  type: image
  params:
  - name: url
    value: "gcr.io/teich-gitops/ci-redisslave" # {"type":"string","x-kustomize":{"setter":{"name":"gcr_img_1","value":"gcr.io/teich-gitops/ci-redisslave"}}}
