apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: guestbook-web-image
  namespace: "ci" # {"type":"string","x-kustomize":{"setter":{"name":"namespace","value":"ci"}}}
spec:
  type: image
  params:
  - name: url
    value: "gcr.io/teich-gitops/ci-frontend" # {"type":"string","x-kustomize":{"setter":{"name":"gcr_img_2","value":"gcr.io/teich-gitops/ci-frontend"}}}
